sudo: required

language: go

go:
  - master

services:
  - docker

before_install:
  - echo $TRAVIS_GO_VERSION
  - docker pull ckeyer/dev:go
  - docker pull ckeyer/dev:node

script:
  - make test
  - make image

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make push