// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/controller.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	protos/controller.proto
	protos/daemon.proto
	protos/node_info.proto

It has these top-level messages:
	Node
	Task
	NodeStatus
	NodeInfo
	HTTPOption
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	Info *NodeInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetInfo() *NodeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Task struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NodeStatus struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *NodeStatus) Reset()                    { *m = NodeStatus{} }
func (m *NodeStatus) String() string            { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()               {}
func (*NodeStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NodeInfo struct {
	Hostname   string   `protobuf:"bytes,1,opt,name=Hostname,json=hostname" json:"Hostname,omitempty"`
	Ips        []string `protobuf:"bytes,2,rep,name=Ips,json=ips" json:"Ips,omitempty"`
	MemoryUsed int64    `protobuf:"varint,3,opt,name=MemoryUsed,json=memoryUsed" json:"MemoryUsed,omitempty"`
	Memory     int64    `protobuf:"varint,4,opt,name=Memory,json=memory" json:"Memory,omitempty"`
	CpuUsed    float32  `protobuf:"fixed32,5,opt,name=CpuUsed,json=cpuUsed" json:"CpuUsed,omitempty"`
	NumCpus    int64    `protobuf:"varint,6,opt,name=NumCpus,json=numCpus" json:"NumCpus,omitempty"`
	NumPhyCpus int64    `protobuf:"varint,7,opt,name=NumPhyCpus,json=numPhyCpus" json:"NumPhyCpus,omitempty"`
	LoadAvg    float32  `protobuf:"fixed32,8,opt,name=LoadAvg,json=loadAvg" json:"LoadAvg,omitempty"`
	Uptime     string   `protobuf:"bytes,9,opt,name=Uptime,json=uptime" json:"Uptime,omitempty"`
	UnixTime   int64    `protobuf:"varint,10,opt,name=UnixTime,json=unixTime" json:"UnixTime,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NodeInfo) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *NodeInfo) GetMemoryUsed() int64 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *NodeInfo) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *NodeInfo) GetCpuUsed() float32 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *NodeInfo) GetNumCpus() int64 {
	if m != nil {
		return m.NumCpus
	}
	return 0
}

func (m *NodeInfo) GetNumPhyCpus() int64 {
	if m != nil {
		return m.NumPhyCpus
	}
	return 0
}

func (m *NodeInfo) GetLoadAvg() float32 {
	if m != nil {
		return m.LoadAvg
	}
	return 0
}

func (m *NodeInfo) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *NodeInfo) GetUnixTime() int64 {
	if m != nil {
		return m.UnixTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Node)(nil), "ckeyer.com.spongebob.protos.Node")
	proto.RegisterType((*Task)(nil), "ckeyer.com.spongebob.protos.Task")
	proto.RegisterType((*NodeStatus)(nil), "ckeyer.com.spongebob.protos.NodeStatus")
	proto.RegisterType((*NodeInfo)(nil), "ckeyer.com.spongebob.protos.NodeInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Controller service

type ControllerClient interface {
	Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Task, error)
	ReportStatus(ctx context.Context, opts ...grpc.CallOption) (Controller_ReportStatusClient, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := grpc.Invoke(ctx, "/ckeyer.com.spongebob.protos.Controller/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ReportStatus(ctx context.Context, opts ...grpc.CallOption) (Controller_ReportStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Controller_serviceDesc.Streams[0], c.cc, "/ckeyer.com.spongebob.protos.Controller/ReportStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerReportStatusClient{stream}
	return x, nil
}

type Controller_ReportStatusClient interface {
	Send(*NodeStatus) error
	Recv() (*Task, error)
	grpc.ClientStream
}

type controllerReportStatusClient struct {
	grpc.ClientStream
}

func (x *controllerReportStatusClient) Send(m *NodeStatus) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controllerReportStatusClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Controller service

type ControllerServer interface {
	Join(context.Context, *Node) (*Task, error)
	ReportStatus(Controller_ReportStatusServer) error
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ckeyer.com.spongebob.protos.Controller/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Join(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ReportStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServer).ReportStatus(&controllerReportStatusServer{stream})
}

type Controller_ReportStatusServer interface {
	Send(*Task) error
	Recv() (*NodeStatus, error)
	grpc.ServerStream
}

type controllerReportStatusServer struct {
	grpc.ServerStream
}

func (x *controllerReportStatusServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controllerReportStatusServer) Recv() (*NodeStatus, error) {
	m := new(NodeStatus)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ckeyer.com.spongebob.protos.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Controller_Join_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportStatus",
			Handler:       _Controller_ReportStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/controller.proto",
}

func init() { proto.RegisterFile("protos/controller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x3f, 0x6f, 0xd4, 0x30,
	0x14, 0x97, 0x2f, 0x69, 0x92, 0x7b, 0x74, 0xa8, 0x3c, 0x80, 0x15, 0x10, 0x0a, 0x91, 0x10, 0x51,
	0x87, 0x04, 0x95, 0x89, 0x6e, 0xe5, 0x16, 0x8a, 0xe0, 0x84, 0x42, 0x6f, 0x61, 0x40, 0xca, 0xe5,
	0xdc, 0xd4, 0x34, 0xf1, 0xb3, 0x62, 0x07, 0x71, 0x2b, 0x1f, 0x01, 0x3e, 0x1a, 0x5f, 0x80, 0x81,
	0x0f, 0x82, 0x6c, 0x1f, 0x27, 0x06, 0xd4, 0x76, 0x4a, 0x7e, 0xef, 0xf7, 0xcf, 0x4f, 0x0f, 0x1e,
	0xa8, 0x11, 0x0d, 0xea, 0xaa, 0x45, 0x69, 0x46, 0xec, 0x7b, 0x3e, 0x96, 0x6e, 0x42, 0x1f, 0xb6,
	0xd7, 0x7c, 0xcb, 0xc7, 0xb2, 0xc5, 0xa1, 0xd4, 0x0a, 0x65, 0xc7, 0xd7, 0xb8, 0xf6, 0x9c, 0x4e,
	0x1f, 0x75, 0x88, 0x5d, 0xcf, 0xab, 0x46, 0x89, 0xaa, 0x91, 0x12, 0x4d, 0x63, 0x04, 0x4a, 0xed,
	0xe9, 0xfc, 0x0c, 0xc2, 0x25, 0x6e, 0x38, 0x7d, 0x09, 0xa1, 0x90, 0x97, 0xc8, 0x48, 0x46, 0x8a,
	0x7b, 0x27, 0x4f, 0xcb, 0x1b, 0x12, 0x4b, 0x6b, 0x38, 0x97, 0x97, 0x58, 0x3b, 0x4b, 0x9e, 0x42,
	0x78, 0xd1, 0xe8, 0x6b, 0x4a, 0x21, 0x94, 0xcd, 0xc0, 0x5d, 0xc4, 0xbc, 0x76, 0xff, 0x79, 0x06,
	0x60, 0xd5, 0x1f, 0x4c, 0x63, 0x26, 0xfd, 0x5f, 0xc5, 0xf7, 0x19, 0x24, 0x7f, 0x03, 0x69, 0x0a,
	0xc9, 0x6b, 0xd4, 0xe6, 0x1f, 0x51, 0x72, 0xb5, 0xc3, 0xf4, 0x08, 0x82, 0x73, 0xa5, 0xd9, 0x2c,
	0x0b, 0x8a, 0x79, 0x1d, 0x08, 0xa5, 0xe9, 0x63, 0x80, 0x77, 0x7c, 0xc0, 0x71, 0xbb, 0xd2, 0x7c,
	0xc3, 0x82, 0x8c, 0x14, 0x41, 0x0d, 0xc3, 0x7e, 0x42, 0xef, 0x43, 0xe4, 0x79, 0x16, 0x3a, 0x2e,
	0xf2, 0x1c, 0x65, 0x10, 0x2f, 0xd4, 0xe4, 0x4c, 0x07, 0x19, 0x29, 0x66, 0x75, 0xdc, 0x7a, 0x68,
	0x99, 0xe5, 0x34, 0x2c, 0xd4, 0xa4, 0x59, 0xe4, 0x2c, 0xb1, 0xf4, 0xd0, 0x76, 0x2d, 0xa7, 0xe1,
	0xfd, 0xd5, 0xd6, 0x91, 0xb1, 0xef, 0x92, 0xfb, 0x89, 0x75, 0xbe, 0xc5, 0x66, 0x73, 0xf6, 0xa5,
	0x63, 0x89, 0xcf, 0xec, 0x3d, 0xb4, 0xaf, 0x58, 0x29, 0x23, 0x06, 0xce, 0xe6, 0x6e, 0xa3, 0x68,
	0x72, 0xc8, 0xee, 0xba, 0x92, 0xe2, 0xeb, 0x85, 0x65, 0xc0, 0xe5, 0x25, 0xd3, 0x0e, 0x9f, 0xfc,
	0x22, 0x00, 0x8b, 0xfd, 0x95, 0xe9, 0x27, 0x08, 0xdf, 0xa0, 0x90, 0xf4, 0xc9, 0xad, 0x67, 0x49,
	0x6f, 0x96, 0xd8, 0x3b, 0xe5, 0x47, 0xdf, 0x7e, 0xfe, 0xfe, 0x31, 0x83, 0xfc, 0xa0, 0xfa, 0x8c,
	0x42, 0x9e, 0x92, 0x63, 0x3a, 0xc2, 0x61, 0xcd, 0x15, 0x8e, 0x66, 0x77, 0xa7, 0x67, 0xb7, 0xf6,
	0x78, 0xe1, 0x5d, 0xda, 0xa8, 0x6b, 0x3b, 0xcc, 0xe3, 0x4a, 0x3b, 0xcf, 0x29, 0x39, 0x2e, 0xc8,
	0x73, 0xf2, 0x2a, 0xf9, 0x18, 0x79, 0xd9, 0xda, 0x7f, 0x5f, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xd4, 0x31, 0x0b, 0xaa, 0xdf, 0x02, 0x00, 0x00,
}
