// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task_server.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import ckeyer_api2 "github.com/ckeyer/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HostDaemon service

type HostDaemonClient interface {
	StartHTTP(ctx context.Context, in *ckeyer_api2.HTTPOption, opts ...grpc.CallOption) (*ckeyer_api2.HTTPOption, error)
	StopHTTP(ctx context.Context, in *ckeyer_api2.HTTPOption, opts ...grpc.CallOption) (*ckeyer_api2.HTTPOption, error)
}

type hostDaemonClient struct {
	cc *grpc.ClientConn
}

func NewHostDaemonClient(cc *grpc.ClientConn) HostDaemonClient {
	return &hostDaemonClient{cc}
}

func (c *hostDaemonClient) StartHTTP(ctx context.Context, in *ckeyer_api2.HTTPOption, opts ...grpc.CallOption) (*ckeyer_api2.HTTPOption, error) {
	out := new(ckeyer_api2.HTTPOption)
	err := grpc.Invoke(ctx, "/ckeyer.com.spongebob.protos.HostDaemon/StartHTTP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostDaemonClient) StopHTTP(ctx context.Context, in *ckeyer_api2.HTTPOption, opts ...grpc.CallOption) (*ckeyer_api2.HTTPOption, error) {
	out := new(ckeyer_api2.HTTPOption)
	err := grpc.Invoke(ctx, "/ckeyer.com.spongebob.protos.HostDaemon/StopHTTP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HostDaemon service

type HostDaemonServer interface {
	StartHTTP(context.Context, *ckeyer_api2.HTTPOption) (*ckeyer_api2.HTTPOption, error)
	StopHTTP(context.Context, *ckeyer_api2.HTTPOption) (*ckeyer_api2.HTTPOption, error)
}

func RegisterHostDaemonServer(s *grpc.Server, srv HostDaemonServer) {
	s.RegisterService(&_HostDaemon_serviceDesc, srv)
}

func _HostDaemon_StartHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ckeyer_api2.HTTPOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostDaemonServer).StartHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ckeyer.com.spongebob.protos.HostDaemon/StartHTTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostDaemonServer).StartHTTP(ctx, req.(*ckeyer_api2.HTTPOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostDaemon_StopHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ckeyer_api2.HTTPOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostDaemonServer).StopHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ckeyer.com.spongebob.protos.HostDaemon/StopHTTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostDaemonServer).StopHTTP(ctx, req.(*ckeyer_api2.HTTPOption))
	}
	return interceptor(ctx, in, info, handler)
}

var _HostDaemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ckeyer.com.spongebob.protos.HostDaemon",
	HandlerType: (*HostDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartHTTP",
			Handler:    _HostDaemon_StartHTTP_Handler,
		},
		{
			MethodName: "StopHTTP",
			Handler:    _HostDaemon_StopHTTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_server.proto",
}

func init() { proto.RegisterFile("task_server.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x49, 0x2c, 0xce,
	0x8e, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4e,
	0xce, 0x4e, 0xad, 0x4c, 0x2d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2b, 0x2e, 0xc8, 0xcf, 0x4b, 0x4f,
	0x4d, 0xca, 0x4f, 0x82, 0xc8, 0x15, 0x4b, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27,
	0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0xa4,
	0xa5, 0xd4, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0x40, 0x5a, 0xf5, 0x21, 0xa6, 0x80, 0x15, 0x66,
	0x94, 0x94, 0x14, 0xc4, 0xe7, 0x17, 0x80, 0x54, 0x42, 0x14, 0x1a, 0x75, 0x32, 0x72, 0x71, 0x79,
	0xe4, 0x17, 0x97, 0xb8, 0x24, 0xa6, 0xe6, 0xe6, 0xe7, 0x09, 0xd9, 0x72, 0x71, 0x06, 0x97, 0x24,
	0x16, 0x95, 0x78, 0x84, 0x84, 0x04, 0x08, 0x89, 0xe9, 0x41, 0x1d, 0x90, 0x58, 0x90, 0xa9, 0x07,
	0x12, 0xf1, 0x07, 0xeb, 0x94, 0xc2, 0x21, 0xae, 0xc4, 0x20, 0x64, 0xc3, 0xc5, 0x11, 0x5c, 0x92,
	0x5f, 0x40, 0x9e, 0x6e, 0x27, 0x8e, 0x28, 0x36, 0x88, 0xe7, 0x92, 0x20, 0xb4, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x15, 0x6a, 0x89, 0x15, 0x01, 0x00, 0x00,
}
